### ISSUE TITLE
Hiro Ordinals API mime type query param documentation and implementation mismatch

### ISSUE THREAD

**Issue by thecolorblocks** [hirosystems/ordinals-explorer#101]
**Describe the bug**
Documentation states `mime_type` query param for `/inscriptions` endpoint is array of mime types, which produces 400 Bad Request error: `querystring/mime_type/0 must match pattern \"^\\w+\\/[-.\\w]+(?:\\+[-.\\w]+)?$\"`

**To Reproduce**
1. Go to https://docs.hiro.so/ordinals/list-of-inscriptions
2. Click on 'Show optional parameters' on the right
3. Scroll down to '`mime_type` -- query' and click on 'Add item'
4. Add two valid mime types, such as `image/jpeg` and `image/png`
5. Scroll down and click execute. See error response
```json
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "querystring/mime_type/0 must match pattern \"^\\w+\\/[-.\\w]+(?:\\+[-.\\w]+)?$\""
}
```

**Expected behavior**
Return 200 success

**Screenshots**
If applicable, add screenshots or consol.log to help explain your problem.
![Screenshot 2023-11-11 203343](https://github.com/hirosystems/ordinals-explorer/assets/129370525/0c794888-47c8-4f7d-8d67-bc70b08ef7dd)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Opera (Chromium)
 - Version 104.0.4944.36

**Comment by janniks** [comment]
Thanks for the report, I‘ll try to fix the docs.
If you want to use the API it should be enough to encode to parameter as a URI component https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

**Comment by thecolorblocks** [comment]
> Thanks for the report, I‘ll try to fix the docs. If you want to use the API it should be enough to encode to parameter as a URI component https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

So does the API supports multiple mime types or just a single mime type at this time? Would love to implement file type filtering but filtering for specific file extensions do not seem user friendly, otherwise would have to fetch the API multiple times for different image file extensions and consolidate to return the "image" type inscriptions. Same goes for audio, video, and so on.
