### ISSUE TITLE
Add Newsletter Box (aka email capture) in the footer of the Ordinals Explorer

### ISSUE THREAD

**Issue by elenananana** [hirosystems/ordinals-explorer#104]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Similar to the newletter box/ email capture on hiro.so, I'd like to include an email capture at the bottom of the ordinals explorer. 
<img width="527" alt="Screenshot 2024-01-30 at 4 19 55 PM" src="https://github.com/hirosystems/ordinals-explorer/assets/62673553/7ecb5f84-4333-451c-9b44-58fde3e5787a">

**Comment by janniks** [comment]
Completed in https://github.com/hirosystems/ordinals-explorer/pull/106
