### ISSUE TITLE
Recent ordinal transfer not indexed (7 hours ago)

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/ordinals-explorer#108]
**Describe the bug**
I do not see any ordinals reflected on the [ordinals.hiro.so](http://ordinals.hiro.so/) explorer
it was transferred to the taproot address of a Leather wallet here https://mempool.space/tx/0bec59c00c959b53f42675107059449c3cb69f043c5893cb4f73f93dd0651260
but the change is not reflected, the transfer was confirmed 7 hours ago. 

https://ordinals.hiro.so/address/bc1ptuah74r5xu9lsmtthaqqqwguqmwn2fgpygegzaj7f5w7k5sc8qcqcks0r6 

![image](https://github.com/hirosystems/ordinals-explorer/assets/33360391/d0270c55-0d8e-460d-bb7a-b45c069ffd88)

I do see one in [ord.io](http://ord.io/) 
https://www.ord.io/bc1ptuah74r5xu9lsmtthaqqqwguqmwn2fgpygegzaj7f5w7k5sc8qcqcks0r6

63,302,112
https://ordinals.hiro.so/inscription/f701bcfd929611e595611a1fcd3d45deb88eb1178c23626679a644fc46546fe0i0
looks like the change is not yet indexed by the Hiro browser

I see on this explorer it also transferred the tokens alright
https://bestinslot.xyz/ordinals/inscription/63302112 to 
https://bestinslot.xyz/bc1ptuah74r5xu9lsmtthaqqqwguqmwn2fgpygegzaj7f5w7k5sc8qcqcks0r6#type=brc20

![image](https://github.com/hirosystems/ordinals-explorer/assets/33360391/9426c6a7-d7a4-498e-9f78-47c7ebea693a)

![image](https://github.com/hirosystems/ordinals-explorer/assets/33360391/022c7700-5fed-4dbb-91a8-9a46241f8779)

Transaction ID https://mempool.space/tx/0bec59c00c959b53f42675107059449c3cb69f043c5893cb4f73f93dd0651260
Address bc1ptuah74r5xu9lsmtthaqqqwguqmwn2fgpygegzaj7f5w7k5sc8qcqcks0r6
Block#  833206
Time stamp ‎2024-03-05 06:40 (8 hours ago)

**To Reproduce**
n.a. see above

**Expected behavior**
I expect recent token to be displayed on the explorer.

**Comment by lgalabru** [comment]
Addressed with latest I believe
