### ISSUE TITLE
Email capture design updates

### ISSUE THREAD

**Issue by andromeda995** [hirosystems/ordinals-explorer#28]
[Link to Figma mocks here](https://www.figma.com/file/31q1g27k69z1yXb6r6vrRD/Explorer?node-id=4732%3A34030&t=jUEoLcHAfncwDwfg-1)

Modifications to the header and footer to accommodate email capture to Hiro's newsletter

**Comment by smcclellan** [comment]
@andromeda995 What's the next step, who would you like a review from?

**Comment by smcclellan** [comment]
Closing as this seems complete. Feel free to reopen if more work is needed.
