### ISSUE TITLE
Add BRC-20 specific features

### ISSUE THREAD

**Issue by markmhx** [hirosystems/ordinals-explorer#37]
The latest inscriptions are dominated by them but there's no way to parse through the data (e.g. how many of each ticker is getting minted per day, by how many addresses, etc...there are lots of possibilities).

The creator of BRC-20, Domo, asked in a chat if we were working on explorer-related enhancements, so he could provide ideas as well (though we'll need to open source this repo to make that easy?).

A starting point could be UniSat's page here: https://unisat.io/brc20

<img width="1092" alt="Screenshot 2023-05-28 at 21 53 21" src="https://github.com/hirosystems/ordinals-explorer/assets/28991/6f6ccd7b-1b4c-4a5f-8863-c518cd26e5c5">

**Comment by smcclellan** [comment]
Thank you for this ticket, @markmhx! The ordinals-explorer repo is actually open-sourced now, so all discussion can happen here.

I've created [this stub ticket](https://github.com/hirosystems/ordinals-explorer/issues/75) where we'll track the BRC-20 work on the explorer side. Please feel free to put any extra info, requests, ideas in there. I'll close this ticket to direct discussion there. By the way, the screenshot you have here isn't loading on my end.

**Comment by markmhx** [comment]
Thanks! IIRC the screenshot was just of the Ordinals Explorer's homepage, showing a bunch of BRC-20 inscriptions displayed as JSON.
